messages:
  command-in-console: '&cYou cant use this command in console!'
  no-life-placeholder: '&cBe careful! You have last life.'
  unknown-player: '&cUnknown player!'
  number-of-life: '&aYour life: %life%'
  number-of-life-player: '&aLife of %player% is: %life%'
  no-permission: '&cYou dont have permission to this command!'
  add-life-success: '&aYou add %number% life to %player%!'
  remove-life-success: '&cYou remove %number% life from %player%!'
  set-life-success: '&aYou set %number% life to %player%!'
  give-life-success: '&aYou gave %number% life to %target%!'
  give-life-success-to-target: '&aYou received %number% life from %player%!'
  give-life-error: '&cYou must have at least 1 life!'
  item-add-life-success: '&aYou received item!'
  invalid-usage: '&cInvalid usage of command!'
  perm-ban-reason: '&cYou have been banned permanently for the lack of lives!'
  temp-ban-reason: '&cYou have been banned temporarily for the lack of lives. Ban passes for %time%'
  reload-message: '&aYou successfully reloaded config!'
  number-exception: '&cThis isnt number!'
  life-number-exception: '&cGiven number isnt positive!'
  self-give-life: '&cYou cant give life yourself!'
  message-on-death: '&cYou lost %number% life.'
  message-on-click: '&aYou received %number% life.'
  days: '&cdays'
  hours: '&chours'
  minutes: '&cminutes'

ban:
  perm: false
  days: 0
  hours: 1
  minutes: 1

settings:
  starting-life-number: 3
  remove-life-on-death-number: 1
  enable-message-on-death: true

add-life-item:
  enabled: true
  enable-message-on-click: true
  name: '&cLife %number%'
  material: 'RED_WOOL'
  life-to-add: 1
  lore:
    - '&aClick to get %number% life!'

world-guard:
  enabled: true
  regions:
    - 'spawn'

