language: 'en'

ban:
  perm: false
  days: 0
  hours: 1
  minutes: 1

settings:
  starting-life-number: 3
  remove-life-on-death-number: 1
  enable-message-on-death: true

add-life-item:
  enabled: true
  enable-message-on-click: true
  material: 'RED_WOOL'
  life-to-add: 1
  name: '&cLife %number%'
  lore:
    - '&aClick to get %number% life'

world-guard:
  enabled: false
  regions:
    - 'spawn'


version: '1.2'