messages:
  command-in-console: '&cNie możesz wykonać tej komendy w konsoli!'
  no-life-placeholder: '&cUważaj! Masz ostatnie życie.'
  unknown-player: '&cTen gracz nie grał na serwerze!'
  number-of-life: '&aTwoja ilość żyć to: %life%'
  number-of-life-player: '&aIlość żyć gracza %player% wynosi: %life%'
  no-permission: '&cNie masz wystarczających permisji!'
  add-life-success: '&aDodałeś graczowi %player% %number% żyć!'
  remove-life-success: '&cUsunąłeś graczowi %player% %number% żyć!'
  set-life-success: '&aUstawiłeś graczowi %player% %number% żyć!'
  item-add-life-success: '&aOdebrałeś item!'
  invalid-usage: '&cZłe wykonanie komendy!!'
  perm-ban-reason: '&cZostałeś zbanowany pernamentnie za brak żyć!'
  temp-ban-reason: '&cZostałeś zbanowany za brak żyć. Ban mija za %time%'
  reload-message: '&aPomyślnie przeładowano config!'
  number-exception: '&cPodany tekst nie jest liczbą!'
  life-number-exception: '&cPodana liczba nie jest dodatnia!'
  message-on-death: '&cStraciłeś %number% żyć'
  message-on-click: '&aDostałeś %number% żyć'
  days: '&cdzień/dni'
  hours: '&cgodzin/e'
  minutes: '&cminut/y'

ban:
  perm: false
  days: 0
  hours: 1
  minutes: 1

settings:
  starting-life-number: 3
  remove-life-on-death-number: 1
  enable-message-on-death: true

add-life-item:
  enabled: true
  enable-message-on-click: true
  name: '&cŻycia %number%'
  material: 'RED_WOOL'
  number: 1
  lore:
    - '&aKliknij aby uzyskać %number% żyć'

world-guard:
  enabled: true
  regions:
    - 'spawn'
