name: Life
version: '${project.version}'
main: me.nes0x.life.Main
api-version: 1.16
authors: [ Nes0x ]

softdepend:
  - PlaceholderAPI

commands:
  life:
    aliases:
      - zycia

permissions:
  life.commands.add:
    description: Permission to command /life add <nick> <number>
    default: op
  life.commands.remove:
    description: Permission to command /life remove <nick> <number>
    default: op
  life.commands.set:
    description: Permission to command /life set <nick <number>
    default: op
  life.commands.item:
    description: Permission to command /life item
    default: op
  life.commands.reload:
    description: Permission to command /life reload
    default: op
