name: Life
version: '${project.version}'
main: me.nes0x.life.Life
api-version: 1.13
authors: [ Nes0x ]

softdepend:
  - PlaceholderAPI
  - WorldGuard


permissions:
  life.command.add:
    description: Access to command /life add <nick> <amount>
    default: op
  life.command.remove:
    description: Access to command /life remove <nick> <amount>
    default: op
  life.command.set:
    description: Access to command /life set <nick <amount>
    default: op
  life.command.item:
    description: Access to command /life item
    default: op
  life.command.reload:
    description: Access to command /life reload
    default: op
  life.command.give:
    description: Access to command /life give <nick> <amount>
    default: op
  life.command.*:
    description: Access to all commands
    default: op
    children:
      life.command.add: true
      life.command.remove: true
      life.command.set: true
      life.command.item: true
      life.command.reload: true
      life.command.give: true