name: Life
version: '${project.version}'
main: me.nes0x.life.Life
api-version: 1.13
authors: [ Nes0x ]

softdepend:
  - PlaceholderAPI
  - WorldGuard

commands:
  life:
    aliases:
      - zycia

permissions:
  life.command.add:
    description: Access to command /life add <nick> <number>
    default: op
  life.command.remove:
    description: Access to command /life remove <nick> <number>
    default: op
  life.command.set:
    description: Access to command /life set <nick <number>
    default: op
  life.command.item:
    description: Access to command /life item
    default: op
  life.command.reload:
    description: Access to command /life reload
    default: op
  life.command.give:
    description: Access to command /life give <nick> <number>
    default: op
  life.command.*:
    description: Access to all commands
    default: op
    children:
      life.commands.add: true
      life.commands.remove: true
      life.commands.set: true
      life.commands.item: true
      life.commands.reload: true
      life.commands.give: true