name: Life
version: '${project.version}'
main: me.nes0x.life.Main
api-version: 1.16
authors: [ Nes0x ]

softdepend:
  - PlaceholderAPI
  - WorldGuard

commands:
  life:
    aliases:
      - zycia

permissions:
  life.commands.add:
    description: Access to command /life add <nick> <number>
    default: op
  life.commands.remove:
    description: Access to command /life remove <nick> <number>
    default: op
  life.commands.set:
    description: Access to command /life set <nick <number>
    default: op
  life.commands.item:
    description: Access to command /life item
    default: op
  life.commands.reload:
    description: Access to command /life reload
    default: op
  life.commands.*:
    description: Access to all commands
    default: op
    children:
      life.commands.add: true
      life.commands.remove: true
      life.commands.set: true
      life.commands.item: true
      life.commands.reload: true